/**
 * PostgreSQL schema for Saiyan Protocol.
 * Run via the migrate script — all statements use IF NOT EXISTS.
 */
export const SCHEMA_SQL = `

-- ═══════════════════════════════════
-- Enable UUID generation
-- ═══════════════════════════════════
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ═══════════════════════════════════
-- Athlete profile (multi-user)
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS athletes (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  google_id     TEXT NOT NULL UNIQUE,
  email         TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL DEFAULT '',
  picture_url   TEXT NOT NULL DEFAULT '',
  age           INTEGER NOT NULL DEFAULT 0,
  height        TEXT NOT NULL DEFAULT '',
  weight        TEXT NOT NULL DEFAULT '',
  power_level   INTEGER NOT NULL DEFAULT 1000,
  current_block INTEGER NOT NULL DEFAULT 1,
  current_week  INTEGER NOT NULL DEFAULT 1,
  total_sessions_completed INTEGER NOT NULL DEFAULT 0,
  streak_days   INTEGER NOT NULL DEFAULT 0,
  five_km_time  TEXT NOT NULL DEFAULT '',
  fitness_experience TEXT NOT NULL DEFAULT '',
  training_goal TEXT NOT NULL DEFAULT '',
  selected_goals JSONB NOT NULL DEFAULT '[]'::jsonb,
  onboarded     BOOLEAN NOT NULL DEFAULT FALSE,
  plan_intro_seen BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE athletes ADD COLUMN IF NOT EXISTS fitness_experience TEXT NOT NULL DEFAULT '';
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS training_goal TEXT NOT NULL DEFAULT '';
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS selected_goals JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE athletes ADD COLUMN IF NOT EXISTS plan_intro_seen BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE athletes DROP COLUMN IF EXISTS twelve_week_goal;

-- ═══════════════════════════════════
-- AI-generated training plan summary
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS training_plans (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id  UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  total_weeks INTEGER NOT NULL CHECK (total_weeks > 0),
  summary     TEXT NOT NULL DEFAULT '',
  coach_note  TEXT NOT NULL DEFAULT '',
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS training_plan_blocks (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id      UUID NOT NULL REFERENCES training_plans(id) ON DELETE CASCADE,
  block_number INTEGER NOT NULL,
  name         TEXT NOT NULL,
  start_week   INTEGER NOT NULL,
  end_week     INTEGER NOT NULL,
  focus        TEXT NOT NULL DEFAULT '',
  sort_order   INTEGER NOT NULL DEFAULT 0,
  UNIQUE(plan_id, block_number)
);

-- ═══════════════════════════════════
-- Weekly schedule generated by AI
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS week_schedules (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id       UUID REFERENCES training_plans(id) ON DELETE SET NULL,
  athlete_id    UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  week          INTEGER NOT NULL,
  block         INTEGER NOT NULL,
  block_name    TEXT NOT NULL,
  weekly_intent TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(athlete_id, week, block)
);

ALTER TABLE week_schedules ADD COLUMN IF NOT EXISTS plan_id UUID REFERENCES training_plans(id) ON DELETE SET NULL;

-- ═══════════════════════════════════
-- Individual workouts within a week
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS workouts (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id        UUID NOT NULL REFERENCES week_schedules(id) ON DELETE CASCADE,
  day                TEXT NOT NULL,
  type               TEXT NOT NULL,
  title              TEXT NOT NULL,
  subtitle           TEXT NOT NULL,
  estimated_duration TEXT NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════
-- Workout phases (Power Up, Strength, Conditioning, etc.)
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS workout_phases (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workout_id  UUID NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  duration    TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ═══════════════════════════════════
-- Exercises within phases
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS exercises (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phase_id    UUID NOT NULL REFERENCES workout_phases(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT NOT NULL,
  cue         TEXT NOT NULL,
  sets        INTEGER NOT NULL,
  reps        TEXT NOT NULL,
  rest        TEXT NOT NULL,
  substitute  TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ═══════════════════════════════════
-- Session logs — one per completed workout
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS session_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id    UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  workout_id    UUID NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
  date          DATE NOT NULL,
  completed     BOOLEAN NOT NULL DEFAULT FALSE,
  effort_rating INTEGER NOT NULL DEFAULT 5 CHECK (effort_rating BETWEEN 1 AND 10),
  notes         TEXT NOT NULL DEFAULT '',
  duration      INTEGER NOT NULL DEFAULT 0,
  power_gained  INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════
-- Per-exercise logs within a session
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS exercise_logs (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_log_id UUID NOT NULL REFERENCES session_logs(id) ON DELETE CASCADE,
  exercise_id    UUID NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  exercise_name  TEXT NOT NULL,
  notes          TEXT NOT NULL DEFAULT '',
  completed      BOOLEAN NOT NULL DEFAULT FALSE
);

-- ═══════════════════════════════════
-- Individual set logs within an exercise log
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS set_logs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_log_id UUID NOT NULL REFERENCES exercise_logs(id) ON DELETE CASCADE,
  set_number      INTEGER NOT NULL,
  reps            INTEGER,
  weight          REAL,
  time_seconds    INTEGER,
  completed       BOOLEAN NOT NULL DEFAULT FALSE
);

-- ═══════════════════════════════════
-- AI generation history
-- ═══════════════════════════════════
CREATE TABLE IF NOT EXISTS ai_generation_logs (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id       UUID NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
  call_type        TEXT NOT NULL,
  request_payload  JSONB NOT NULL,
  response_payload JSONB NOT NULL,
  model            TEXT NOT NULL DEFAULT '',
  tokens_used      INTEGER,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════
-- Indexes
-- ═══════════════════════════════════
CREATE INDEX IF NOT EXISTS idx_week_schedules_athlete ON week_schedules(athlete_id);
CREATE INDEX IF NOT EXISTS idx_training_plans_athlete ON training_plans(athlete_id);
CREATE INDEX IF NOT EXISTS idx_training_plan_blocks_plan ON training_plan_blocks(plan_id);
CREATE INDEX IF NOT EXISTS idx_workouts_schedule ON workouts(schedule_id);
CREATE INDEX IF NOT EXISTS idx_workout_phases_workout ON workout_phases(workout_id);
CREATE INDEX IF NOT EXISTS idx_exercises_phase ON exercises(phase_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_athlete ON session_logs(athlete_id);
CREATE INDEX IF NOT EXISTS idx_session_logs_date ON session_logs(date);
CREATE INDEX IF NOT EXISTS idx_exercise_logs_session ON exercise_logs(session_log_id);
CREATE INDEX IF NOT EXISTS idx_set_logs_exercise_log ON set_logs(exercise_log_id);
CREATE INDEX IF NOT EXISTS idx_ai_logs_athlete ON ai_generation_logs(athlete_id);

`;
